version: "3.8"
services:
  otelcol:
    image: otel/opentelemetry-collector:0.12.0
    ports:
      - "55680:55680"
      - "55681:55681"
      - "55678:55678"
      - "55679:55679"
    volumes:
      - ".github/otel-test-config.yaml:/otel-local-config.yaml"
    command: ["--config", "otel-local-config.yaml"]
    links:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  dd-agent:
    image: datadog/agent:7
    ports:
      - "8126:8126"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    environment:
      DD_API_KEY: test