name: Build & Release

on:
  push:
  pull_request:

jobs:
  agent:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project agent; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/agent/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-agent:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent:latest
          docker push janstenpickle/trace4cats-agent:latest

          PAT='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          if [[ $VERSION =~ $PAT ]]; then
            docker tag janstenpickle/trace4cats-agent:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent:$VERSION
            docker push janstenpickle/trace4cats-agent:$VERSION
          else
            exit 0
          fi
          popd

  agent-kafka:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project agent-kafka; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/agent-kafka/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-agent-kafka:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent-kafka:latest
          docker push janstenpickle/trace4cats-agent-kafka:latest

          PAT='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          if [[ $VERSION =~ $PAT ]]; then
            docker tag janstenpickle/trace4cats-agent-kafka:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent-kafka:$VERSION
            docker push janstenpickle/trace4cats-agent-kafka:$VERSION
          else
            exit 0
          fi
          popd

  collector-lite:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project collector-lite; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/collector-lite/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-collector-lite:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-collector-lite:latest
          docker push janstenpickle/trace4cats-collector-lite:latest

          PAT='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          if [[ $VERSION =~ $PAT ]]; then
            docker tag janstenpickle/trace4cats-collector-lite:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-collector-lite:$VERSION
            docker push janstenpickle/trace4cats-collector-lite:$VERSION
          else
            exit 0
          fi
          popd

  collector:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
          PAT='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          if [[ $VERSION =~ $PAT ]]; then
            VERSION="latest"
          fi
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ "; project collector; set version in ThisBuild := \"latest\"; docker:publishLocal" -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          docker tag janstenpickle/trace4cats-collector:latest janstenpickle/trace4cats-collector:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-collector:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-collector:latest

          PAT='^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          if [[ $VERSION =~ $PAT ]]; then
            docker tag janstenpickle/trace4cats-collector:latest janstenpickle/trace4cats-collector:$VERSION
            docker push janstenpickle/trace4cats-collector:$VERSION
          else
            exit 0
          fi

  libraries:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify'
    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: sonatype credentials
        run: |
          cat << EOF > ~/.sbt/sonatype_credentials
          realm=Sonatype Nexus Repository Manager
          host=oss.sonatype.org
          user=${{ secrets.SONATYPE_USER }}
          password=${{ secrets.SONATYPE_PASS }}
          EOF

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASS }}

      - name: scala build
        env:
          PGP_PASS: ${{ secrets.PGP_PASS }}
        run: |
          sbt -Dsona.user=${{ secrets.SONATYPE_USER }} -Dsona.pass=${{ secrets.SONATYPE_PASS }} -Dsbt.coursier.home=~/.sbt/coursier/ +releaseEarly sonatypeBundleRelease -J-Xms3G -J-Xmx6G -J-Xss4m

  test:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        scala-version:
          - "2.12.14"
          - "2.13.6"
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: docker containers
        run: docker-compose up -d

      - name: Cache ivy2
        uses: actions/cache@v2.1.6
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ ++${{ matrix.scala-version }} '; scalafmtCheckAll; scalafmtSbtCheck; compile; test' -J-Xms3G -J-Xmx6G -J-Xss4m
